name: CD Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production-env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Deploy to Production
        run: |
          echo "Deploying to production environment..."
          # Add your deployment commands here